#############################################################################
# Makefile for building: qtPlatz
# Generated by qmake (2.01a) (Qt 4.6.3) on: Fri May 6 12:51:34 2011
# Project:  qtPlatz.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -o Makefile qtPlatz.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src \
		sub-share

src//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/thondo/src/qtPlatz/src/src.pro -unix -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /home/thondo/src/qtPlatz/src/src.pro -unix -o $(MAKEFILE)
sub-src: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
share//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) share/ || $(MKDIR) share/ 
	cd share/ && $(QMAKE) /home/thondo/src/qtPlatz/share/share.pro -unix -o $(MAKEFILE)
sub-share-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) share/ || $(MKDIR) share/ 
	cd share/ && $(QMAKE) /home/thondo/src/qtPlatz/share/share.pro -unix -o $(MAKEFILE)
sub-share: share//$(MAKEFILE) FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE)
sub-share-make_default-ordered: share//$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) 
sub-share-make_default: share//$(MAKEFILE) FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) 
sub-share-make_first-ordered: share//$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) first
sub-share-make_first: share//$(MAKEFILE) FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) first
sub-share-all-ordered: share//$(MAKEFILE) sub-src-all-ordered  FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) all
sub-share-all: share//$(MAKEFILE) FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) all
sub-share-clean-ordered: share//$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) clean
sub-share-clean: share//$(MAKEFILE) FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) clean
sub-share-distclean-ordered: share//$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) distclean
sub-share-distclean: share//$(MAKEFILE) FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) distclean
sub-share-install_subtargets-ordered: share//$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) install
sub-share-install_subtargets: share//$(MAKEFILE) FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) install
sub-share-uninstall_subtargets-ordered: share//$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-share-uninstall_subtargets: share//$(MAKEFILE) FORCE
	cd share/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qtPlatz.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qtPlatz.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile qtPlatz.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
qtPlatz.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile qtPlatz.pro

qmake_all: sub-src-qmake_all sub-share-qmake_all FORCE

make_default: sub-src-make_default-ordered sub-share-make_default-ordered FORCE
make_first: sub-src-make_first-ordered sub-share-make_first-ordered FORCE
all: sub-src-all-ordered sub-share-all-ordered FORCE
clean: sub-src-clean-ordered sub-share-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-share-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-share-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-share-uninstall_subtargets-ordered FORCE

sub-src-check_ordered: src/$(MAKEFILE)
	cd src/ && $(MAKE) check
sub-share-check_ordered: share/$(MAKEFILE) sub-src-check_ordered 
	cd share/ && $(MAKE) check
check: sub-src-check_ordered sub-share-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

