#############################################################################
# Makefile for building: qtPlatz
# Generated by qmake (2.01a) (Qt 4.7.2) on: Mon May 9 11:42:53 2011
# Project:  qtPlatz.pro
# Template: subdirs
# Command: c:\Qt\4.7.2\bin\qmake.exe -o Makefile qtPlatz.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Qt\4.7.2\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-src \
		sub-share

src\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) c:\Users\Toshi.Hondo\src\qtPlatz\src\src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) c:\Users\Toshi.Hondo\src\qtPlatz\src\src.pro -o $(MAKEFILE)
sub-src: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_default: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-make_first: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-all-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-all: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-clean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-distclean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-install_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets-ordered: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-src-uninstall_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall
share\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) share\ $(MKDIR) share\ 
	cd share\ && $(QMAKE) c:\Users\Toshi.Hondo\src\qtPlatz\share\share.pro -o $(MAKEFILE)
sub-share-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) share\ $(MKDIR) share\ 
	cd share\ && $(QMAKE) c:\Users\Toshi.Hondo\src\qtPlatz\share\share.pro -o $(MAKEFILE)
sub-share: share\$(MAKEFILE) FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE)
sub-share-make_default-ordered: share\$(MAKEFILE) sub-src-make_default-ordered  FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) 
sub-share-make_default: share\$(MAKEFILE) FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) 
sub-share-make_first-ordered: share\$(MAKEFILE) sub-src-make_first-ordered  FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) first
sub-share-make_first: share\$(MAKEFILE) FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) first
sub-share-all-ordered: share\$(MAKEFILE) sub-src-all-ordered  FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) all
sub-share-all: share\$(MAKEFILE) FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) all
sub-share-clean-ordered: share\$(MAKEFILE) sub-src-clean-ordered  FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) clean
sub-share-clean: share\$(MAKEFILE) FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) clean
sub-share-distclean-ordered: share\$(MAKEFILE) sub-src-distclean-ordered  FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) distclean
sub-share-distclean: share\$(MAKEFILE) FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) distclean
sub-share-install_subtargets-ordered: share\$(MAKEFILE) sub-src-install_subtargets-ordered  FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) install
sub-share-install_subtargets: share\$(MAKEFILE) FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) install
sub-share-uninstall_subtargets-ordered: share\$(MAKEFILE) sub-src-uninstall_subtargets-ordered  FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-share-uninstall_subtargets: share\$(MAKEFILE) FORCE
	cd share\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qtPlatz.pro  ..\..\..\..\Qt\4.7.2\mkspecs\win32-msvc2008\qmake.conf ..\..\..\..\Qt\4.7.2\mkspecs\qconfig.pri \
		..\..\..\..\Qt\4.7.2\mkspecs\modules\qt_webkit_version.pri \
		..\..\..\..\Qt\4.7.2\mkspecs\features\qt_functions.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\qt_config.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\default_pre.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\default_pre.prf \
		qtPlatz.pri \
		..\..\..\..\Qt\4.7.2\mkspecs\features\debug.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\debug_and_release.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\default_post.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\default_post.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\rtti.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\exceptions.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\stl.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\shared.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\embed_manifest_exe.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\embed_manifest_dll.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\warn_on.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\qt.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\thread.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\moc.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\win32\windows.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\resources.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\uic.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\yacc.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\lex.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\incredibuild_xge.prf \
		..\..\..\..\Qt\4.7.2\mkspecs\features\include_source_dir.prf
	$(QMAKE) -o Makefile qtPlatz.pro
..\..\..\..\Qt\4.7.2\mkspecs\qconfig.pri:
..\..\..\..\Qt\4.7.2\mkspecs\modules\qt_webkit_version.pri:
..\..\..\..\Qt\4.7.2\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\default_pre.prf:
qtPlatz.pri:
..\..\..\..\Qt\4.7.2\mkspecs\features\debug.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\debug_and_release.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\default_post.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\default_post.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\rtti.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\exceptions.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\stl.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\shared.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\embed_manifest_exe.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\embed_manifest_dll.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\qt.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\thread.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\moc.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\win32\windows.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\resources.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\uic.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\yacc.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\lex.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\incredibuild_xge.prf:
..\..\..\..\Qt\4.7.2\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile qtPlatz.pro

qmake_all: sub-src-qmake_all sub-share-qmake_all FORCE

make_default: sub-src-make_default-ordered sub-share-make_default-ordered FORCE
make_first: sub-src-make_first-ordered sub-share-make_first-ordered FORCE
all: sub-src-all-ordered sub-share-all-ordered FORCE
clean: sub-src-clean-ordered sub-share-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-share-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-share-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-share-uninstall_subtargets-ordered FORCE

sub-src-sub_Debug_ordered: src\$(MAKEFILE)
	cd src\ && $(MAKE) debug
sub-share-sub_Debug_ordered: share\$(MAKEFILE) sub-src-sub_Debug_ordered 
	cd share\ && $(MAKE) debug
debug: sub-src-sub_Debug_ordered sub-share-sub_Debug_ordered

sub-src-sub_Release_ordered: src\$(MAKEFILE)
	cd src\ && $(MAKE) release
sub-share-sub_Release_ordered: share\$(MAKEFILE) sub-src-sub_Release_ordered 
	cd share\ && $(MAKE) release
release: sub-src-sub_Release_ordered sub-share-sub_Release_ordered

sub-src-check_ordered: src\$(MAKEFILE)
	cd src\ && $(MAKE) check
sub-share-check_ordered: share\$(MAKEFILE) sub-src-check_ordered 
	cd share\ && $(MAKE) check
check: sub-src-check_ordered sub-share-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

