set ( QTPLATZ_CONFIG_Acquire ${QTPLATZ_SUPPORT_CORBA} )
set ( QTPLATZ_CONFIG_Dataproc 1 )
if ( WIN32 )
  set ( QTPLATZ_CONFIG_Quan 0 )
else()
  set ( QTPLATZ_CONFIG_Quan 1 )  
endif()
set ( QTPLATZ_CONFIG_Sequence 0 )
set ( QTPLATZ_CONFIG_ChemSpider 0 )
set ( QTPLATZ_CONFIG_Chemistry 1 ) 
set ( QTPLATZ_CONFIG_Peptide 1 )
set ( QTPLATZ_CONFIG_Batch 0 )
set ( QTPLATZ_CONFIG_Query 1 )

