set ( QTPLATZ_CONFIG_Acquire ON )
set ( QTPLATZ_CONFIG_Dataproc ON )
set ( QTPLATZ_CONFIG_Quan ON )
set ( QTPLATZ_CONFIG_Sequence OFF )
set ( QTPLATZ_CONFIG_Chemistry ${rdkit_FOUND} )
set ( QTPLATZ_CONFIG_Peptide ON )
set ( QTPLATZ_CONFIG_Batch OFF )
set ( QTPLATZ_CONFIG_Query ON )
