set ( QTPLATZ_CONFIG_Batch     OFF )
set ( QTPLATZ_CONFIG_Sequence  OFF )
set ( QTPLATZ_CONFIG_Cluster   OFF )

if ( IDE_VERSION VERSION_GREATER_EQUAL "9.0.0" )
  set ( QTPLATZ_CONFIG_Servant    ON )
  set ( QTPLATZ_CONFIG_Acquire    ON )
  set ( QTPLATZ_CONFIG_Dataproc   ON )
  set ( QTPLATZ_CONFIG_Quan       ON )

  set ( QTPLATZ_CONFIG_Chemistry  ON )
  set ( QTPLATZ_CONFIG_Peptide    ON )
  set ( QTPLATZ_CONFIG_Query      ON )
  set ( QTPLATZ_CONFIG_Lipidid    ON )
  set ( QTPLATZ_CONFIG_SDFViewer  ON )
  set ( QTPLATZ_CONFIG_Video      OFF )
  set ( QTPLATZ_CONFIG_Example    OFF )
  set ( QTPLATZ_CONFIG_HelloWorld OFF )
elseif( IDE_VERSION VERSION_EQUAL "8.0.2" )
  set ( QTPLATZ_CONFIG_Servant    ON )
  set ( QTPLATZ_CONFIG_Acquire    ON )
  set ( QTPLATZ_CONFIG_Dataproc   ON )
  set ( QTPLATZ_CONFIG_Quan       ON )

  set ( QTPLATZ_CONFIG_Chemistry  ON )
  set ( QTPLATZ_CONFIG_Peptide    OFF )
  set ( QTPLATZ_CONFIG_Query      OFF )
  set ( QTPLATZ_CONFIG_Lipidid    OFF )
  set ( QTPLATZ_CONFIG_SDFViewer  OFF )
  set ( QTPLATZ_CONFIG_Video      OFF )
  set ( QTPLATZ_CONFIG_Example    OFF )
  set ( QTPLATZ_CONFIG_HelloWorld OFF )
else()
  set ( QTPLATZ_CONFIG_Servant    ON )
  set ( QTPLATZ_CONFIG_Acquire    ON )
  set ( QTPLATZ_CONFIG_Dataproc   ON )
  set ( QTPLATZ_CONFIG_Quan       ON )

  set ( QTPLATZ_CONFIG_Chemistry  ${rdkit_FOUND} )
  set ( QTPLATZ_CONFIG_Peptide    ON )
  set ( QTPLATZ_CONFIG_Query      ON )
endif()
