#ifndef DATAANALYSIS_GLOBAL_H
#define DATAANALYSIS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAANALYSIS_LIBRARY)
#  define DATAANALYSISSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAANALYSISSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAANALYSIS_GLOBAL_H
