#ifndef ADORBMGR_GLOBAL_H
#define ADORBMGR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADORBMGR_LIBRARY)
#  define ADORBMGRSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADORBMGRSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADORBMGR_GLOBAL_H
