//////////////////////////////////////////
// Copyright (C) 2010 Toshinobu Hondo, Ph.D.
// Copyright (C) MS-Cheminformatics LLC / Advanced Instrumentation Project
//////////////////////////////////////////
// build setup
// $(ACE_ROOT)\bin\tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I$(TAO_ROOT) $(InputPath)

module GlobalConstants {

    const unsigned long EOR                     = 0xffffffff;
    const unsigned long ClassID_EventLog        = 0x00010001;
    const unsigned long ClassID_InstEvent       = 0x10010002;
    const unsigned long ClassID_MS_BEGIN        = 0x10020000;
    /* reagion in use by tofcontroller, reserved */
    const unsigned long ClassID_MS_END          = 0x1002ffff;

    interface dummy {
    };

};

struct Time_Value {
    unsigned long long sec;
    unsigned long usec;
};
