// This is a -*- C++ -*- header.
//////////////////////////////////////////
// Copyright (C) 2010 Toshinobu Hondo, Ph.D.
// Copyright (C) MS-Cheminformatics LLC / Advanced Instrumentation Project
//
// build setup
// $(ACE_ROOT)\bin\tao_idl -Wb,pre_include=ace/pre.h -Wb,post_include=ace/post.h -I$(TAO_ROOT) $(InputPath)
//////////////////////////////////////////

module SampleBroker {

	enum SampleType { SAMPLE_UNKNOWN, SAMPLE_STANDARD, SAMPLE_QC };

    typedef sequence< string > stringSequence;

	struct SampleSequenceLine {
		string sampleId_;
		SampleType sampType_;
		short stdLevel_;
        short stdReplicates_;
		string vialNumber_;
		string dataName_;
		string ctrlMethodName_;
		string procMethodName_;
		string sampleDescription_;
		string targetMolecules_;  // either list of formula or list of mol-file
		double injVolume_;
        double methodTime_;
		double istdAmount_;       // added amount of ISTD
        stringSequence userValues_;
	};

	interface SampleSequence {
        string getSampleSequenceData();
    };

};

