/**************************************************************************
** Copyright (C) 2010-2011 Toshinobu Hondo, Ph.D.
** Copyright (C) 2013 MS-Cheminformatics LLC
*
** Contact: toshi.hondo@scienceliaison.com
**
** Commercial Usage
**
** Licensees holding valid MS-Cheminformatics commercial licenses may use this file in
** accordance with the MS-Cheminformatics Commercial License Agreement provided with the
** Software or, alternatively, in accordance with the terms contained in
** a written agreement between you and MS-Cheminformatics.
**
** GNU Lesser General Public License Usage
**
** Alternatively, this file may be used under the terms of the GNU Lesser
** General Public License version 2.1 as published by the Free Software
** Foundation and appearing in the file LICENSE.TXT included in the
** packaging of this file.  Please review the following information to
** ensure the GNU Lesser General Public License version 2.1 requirements
** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
**************************************************************************/

module SignalObserver {

    const unsigned long wkEvent_Error           = 0x80000000;
    const unsigned long wkEvent_Warning         = 0x40000000;  // instrument is warning state
    const unsigned long wkEvent_Marker          = 0x20000000;  // wireing to 'marker trigger in'
    const unsigned long wkEvent_INJECT          = 0x10000000;  // wireing to 'inject trigger in'
    const unsigned long wkEvent_MethodStart     = 0x08000000;  // wireing to 'method start in'
    const unsigned long wkEvent_DataWarning     = 0x04000000;  // data waring such as input over range.
    const unsigned long wkEvent_DarkInProgress  = 0x02000000;  // dark signal acquiring
    const unsigned long wkEvent_AcqInProgress   = 0x01000000;  // Data storing, INJ trigger disarmed
    const unsigned long wkEvent_UserEventsMask  = 0x00ffffff;  // wiring to 'event in/out' terminal box

    enum eTRACE_METHOD {
        eTRACE_TRACE
        , eTRACE_SPECTRA
		, eDIAGNOSTIC  // events, LC flow/pressure profile, column oven temp profile etc.
    };

    enum eSPECTROMETER {
        eUnknownSpectrometer
        , eMassSpectrometer
        , eUVSpectrometer
        , eCDSpectrometer
        , eIRSpectrometer
        , eRamanSpectrometer
        , eFluorescenceSpectrometer 
    };

    enum eUpdateFrequency {
        Realtime
        , Friquent
        , Sometimes
        , HalfFull
        , WellKnownEventsOnly
    };

	enum eConfigStatus {
		Offline
		, Online
	};

    struct timeval {
        unsigned long long sec;
        unsigned long usec;
    };
    
    struct Description {
        eTRACE_METHOD trace_method;
        eSPECTROMETER spectrometer;
        wstring trace_id;  // unique name for the trace, can be used as 'data storage name'
        wstring trace_display_name;
        wstring axis_x_label;
        wstring axis_y_label;
        long axis_x_decimals;
        long axis_y_decimals;
    };

    typedef sequence<octet> octet_array;

    struct DataReadBuffer {
        unsigned long long uptime; // time in usec
        unsigned long pos;         // data address (sequencial number for first data in this frame)
        unsigned long ndata;       // number of data (spectra) in array
        unsigned long events;      // well known events
        octet_array xdata;         // encoded data array
        octet_array xmeta;
    };
    
    interface ObserverEvents {
		// Master observer tells you if new device is up or down
		oneway void OnConfigChanged( in unsigned long objId, in eConfigStatus status );

        // OnUpdateData tells you 'new data' at data number 'pos' is now ready to read
        oneway void OnUpdateData( in unsigned long objId, in long pos );

        // OnMethodChanged tells you data monitor parameter has changed at data number 'pos'
        oneway void OnMethodChanged( in unsigned long objId, in long pos );

        // well known event at data number 'pos'
        oneway void OnEvent( in unsigned long objId, in unsigned long event, in long pos );
    };

    interface Observer;

    typedef sequence<Observer> Observers;
    
    interface Observer {

        // getDescription returns description
        Description getDescription();
        boolean setDescription( in Description desc );

        unsigned long objId();
        void assign_objId( in unsigned long oid );

        // client can monitor real time events, it is optional
        boolean connect( in ObserverEvents cb, in eUpdateFrequency frequency, in string token );
        boolean disconnect( in ObserverEvents cb );

        boolean isActive();

        // getSblings returns Observers, which share time base and events.
        // Top level 'Observer' object is responcible to issue events 'OnUpdateData', 'OnEvent', 
        // so application does not need to hookup events for shiblings.
        Observers getSiblings();

        // Instrument controller will add/remove sibling by changing method while running sequence
        boolean addSibling( in Observer observer );
        Observer findObserver( in unsigned long objId, in boolean recursive );

        // uptime returns micro seconds since start moniring, 
        // this number never reset to zero while running
        void uptime( out unsigned long long usec );

		// 
        void uptime_range( out unsigned long long oldest, out unsigned long long newest );

        boolean readData( in long pos, out DataReadBuffer dataReadBuffer );

        // dataInterpreterClsid tells you object location that knows data array structure
        // can turns into meaningfull object such as spectrum or chromatogram
        // this string can be CLSID/GUID for Microsoft COM, 
        // CORBA object name or internal C++ class name that is core software can handle
        wstring dataInterpreterClsid();
        long posFromTime( in unsigned long long usec );
    };
    
};

