// This is a -*- C++ -*- header.
//////////////////////////////////////////
// Copyright (C) 2010 Toshinobu Hondo, Ph.D.
// Science Liaison / Advanced Instrumentation Project
//////////////////////////////////////////

module SignalObserver {

	enum eTRACE_METHOD {
		eTRACE_TRACE
		, eTRACE_SPECTRA
	};

	struct Description {
		wstring trace_id;
		wstring trace_display_name;
		eTRACE_METHOD trace_method;
        wstring axis_x_label;
		wstring axis_y_label;
		wstring axis_x_decimals;
		wstring axis_y_decimals;
	};

	struct Signal {
		sequence< long > data;
	};

	interface Observer {

	};

	interface Session {

	};

};

