// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.9
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:152

#ifndef _TAO_IDL_CONSTANTSC_GKW4FT_H_
#define _TAO_IDL_CONSTANTSC_GKW4FT_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/Object.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 1 || TAO_BETA_VERSION != 9
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_root\root_ch.cpp:160
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace TOF_C
{

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_enum\enum_ch.cpp:47

  enum eIonSource
  {
    eIonSource_Unknown,
    eIonSource_EI,
    eIonSource_DART
  };

  typedef eIonSource &eIonSource_out;

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_eIonSource;

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_enum\enum_ch.cpp:47

  enum ePolarity
  {
    ePolarity_Indeterminate,
    ePolarity_Positive,
    ePolarity_Negative
  };

  typedef ePolarity &ePolarity_out;

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_ePolarity;

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_interface.cpp:750

#if !defined (_TOF_C_NO_EMPTY_FILE__VAR_OUT_CH_)
#define _TOF_C_NO_EMPTY_FILE__VAR_OUT_CH_

  class no_empty_file;
  typedef no_empty_file *no_empty_file_ptr;

  typedef
    TAO_Objref_Var_T<
        no_empty_file
      >
    no_empty_file_var;
  
  typedef
    TAO_Objref_Out_T<
        no_empty_file
      >
    no_empty_file_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  no_empty_file
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<no_empty_file>;

    // TAO_IDL - Generated from
    // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef no_empty_file_ptr _ptr_type;
    typedef no_empty_file_var _var_type;
    typedef no_empty_file_out _out_type;

    static void _tao_any_destructor (void *);

    // The static operations.
    static no_empty_file_ptr _duplicate (no_empty_file_ptr obj);

    static void _tao_release (no_empty_file_ptr obj);

    static no_empty_file_ptr _narrow (::CORBA::Object_ptr obj);
    static no_empty_file_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static no_empty_file_ptr _nil (void);

    // TAO_IDL - Generated from
    // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    no_empty_file (void);

    // Concrete non-local interface only.
    no_empty_file (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    no_empty_file (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);

    virtual ~no_empty_file (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    no_empty_file (const no_empty_file &);

    void operator= (const no_empty_file &);
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\typecode_decl.cpp:37

  extern  ::CORBA::TypeCode_ptr const _tc_no_empty_file;

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module TOF_C

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:904

  template<>
  class Arg_Traits< ::TOF_C::eIonSource>
    : public
        Basic_Arg_Traits_T<
            ::TOF_C::eIonSource,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:904

  template<>
  class Arg_Traits< ::TOF_C::ePolarity>
    : public
        Basic_Arg_Traits_T<
            ::TOF_C::ePolarity,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:147

#if !defined (_TOF_C_NO_EMPTY_FILE__ARG_TRAITS_)
#define _TOF_C_NO_EMPTY_FILE__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::TOF_C::no_empty_file>
    : public
        Object_Arg_Traits_T<
            ::TOF_C::no_empty_file_ptr,
            ::TOF_C::no_empty_file_var,
            ::TOF_C::no_empty_file_out,
            TAO::Objref_Traits<TOF_C::no_empty_file>,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_TOF_C_NO_EMPTY_FILE__TRAITS_)
#define _TOF_C_NO_EMPTY_FILE__TRAITS_

  template<>
  struct  Objref_Traits< ::TOF_C::no_empty_file>
  {
    static ::TOF_C::no_empty_file_ptr duplicate (
        ::TOF_C::no_empty_file_ptr p);
    static void release (
        ::TOF_C::no_empty_file_ptr p);
    static ::TOF_C::no_empty_file_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::TOF_C::no_empty_file_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_enum\any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace TOF_C
{
  

   void operator<<= (::CORBA::Any &, ::TOF_C::eIonSource);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::TOF_C::eIonSource &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, TOF_C::eIonSource);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TOF_C::eIonSource &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_enum\any_op_ch.cpp:39

#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace TOF_C
{
  

   void operator<<= (::CORBA::Any &, ::TOF_C::ePolarity);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::TOF_C::ePolarity &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, TOF_C::ePolarity);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TOF_C::ePolarity &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\any_op_ch.cpp:44



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace TOF_C
{
   void operator<<= ( ::CORBA::Any &, no_empty_file_ptr); // copying
   void operator<<= ( ::CORBA::Any &, no_empty_file_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, no_empty_file_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, TOF_C::no_empty_file_ptr); // copying
 void operator<<= (::CORBA::Any &, TOF_C::no_empty_file_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, TOF_C::no_empty_file_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_enum\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, TOF_C::eIonSource _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, TOF_C::eIonSource &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_enum\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, TOF_C::ePolarity _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, TOF_C::ePolarity &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\cdr_op_ch.cpp:44

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const TOF_C::no_empty_file_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, TOF_C::no_empty_file_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "constantsC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

