// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.9
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:461

#ifndef _TAO_IDL_SIGNALS_F2PNIP_H_
#define _TAO_IDL_SIGNALS_F2PNIP_H_

#include /**/ "ace/pre.h"

#include "signalC.h"
#include "methodS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::IonSource_EI_Setpts>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::IonSource_EI_Setpts,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::IonSource_EI_Actuals>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::IonSource_EI_Actuals,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::IonSource_DART_Setpts>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::IonSource_DART_Setpts,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::IonSource_DART_Actuals>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::IonSource_DART_Actuals,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:1058

  template<>
  class SArg_Traits< ::TOFSignal::IonSourceSetpts>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::IonSourceSetpts,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::tofStaticSetpts>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::tofStaticSetpts,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::tofStaticActs>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::tofStaticActs,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::AnalyzerSetpts>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::AnalyzerSetpts,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::AnalyzerActuals>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::AnalyzerActuals,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::AnalyzerDeviceData>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::AnalyzerDeviceData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::InstEvent>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::InstEvent,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::SpectrumPeakInfo>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::SpectrumPeakInfo,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::TOFSignal::SpectrumPeakInfoVec>
    : public
        Var_Size_SArg_Traits_T<
            ::TOFSignal::SpectrumPeakInfoVec,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::SpectrumProcessedData>
    : public
        Var_Size_SArg_Traits_T<
            ::TOFSignal::SpectrumProcessedData,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::TOFSignal::SpectrumProcessedDataArray>
    : public
        Var_Size_SArg_Traits_T<
            ::TOFSignal::SpectrumProcessedDataArray,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::TraceMetadata>
    : public
        Fixed_Size_SArg_Traits_T<
            ::TOFSignal::TraceMetadata,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::TOFSignal::value_sequence>
    : public
        Var_Size_SArg_Traits_T<
            ::TOFSignal::value_sequence,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::datum>
    : public
        Var_Size_SArg_Traits_T<
            ::TOFSignal::datum,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::TOFSignal::datum_sequence>
    : public
        Var_Size_SArg_Traits_T<
            ::TOFSignal::datum_sequence,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::TOFSignal::tofDATA>
    : public
        Var_Size_SArg_Traits_T<
            ::TOFSignal::tofDATA,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:147

#if !defined (_TOFSIGNAL_NO_EMPTY_FILE__SARG_TRAITS_)
#define _TOFSIGNAL_NO_EMPTY_FILE__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::TOFSignal::no_empty_file>
    : public
        Object_SArg_Traits_T<
            ::TOFSignal::no_empty_file_ptr,
            ::TOFSignal::no_empty_file_var,
            ::TOFSignal::no_empty_file_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_sh.cpp:38

namespace POA_TOFSignal
{
  

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_sh.cpp:76

  class no_empty_file;
  typedef no_empty_file *no_empty_file_ptr;

  class  no_empty_file
    : public virtual PortableServer::ServantBase
  {
  protected:
    no_empty_file (void);
  
  public:
    /// Useful for template programming.
    typedef ::TOFSignal::no_empty_file _stub_type;
    typedef ::TOFSignal::no_empty_file_ptr _stub_ptr_type;
    typedef ::TOFSignal::no_empty_file_var _stub_var_type;

    no_empty_file (const no_empty_file& rhs);
    virtual ~no_empty_file (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::TOFSignal::no_empty_file *_this (void);
    
    virtual const char* _interface_repository_id (void) const;
  };

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_sh.cpp:69

} // module TOFSignal

#include /**/ "ace/post.h"

#endif /* ifndef */

