// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.9
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:461

#ifndef _TAO_IDL_SIOS_KWM4IB_H_
#define _TAO_IDL_SIOS_KWM4IB_H_

#include /**/ "ace/pre.h"

#include "sioC.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Object_SArg_Traits.h"
#include "tao/PortableServer/get_arg.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:147

#if !defined (_SIO_RECEIVER__SARG_TRAITS_)
#define _SIO_RECEIVER__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::SIO::Receiver>
    : public
        Object_SArg_Traits_T<
            ::SIO::Receiver_ptr,
            ::SIO::Receiver_var,
            ::SIO::Receiver_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:147

#if !defined (_SIO_FPGA__SARG_TRAITS_)
#define _SIO_FPGA__SARG_TRAITS_

  template<>
  class  SArg_Traits< ::SIO::FPGA>
    : public
        Object_SArg_Traits_T<
            ::SIO::FPGA_ptr,
            ::SIO::FPGA_var,
            ::SIO::FPGA_out,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_sh.cpp:38

namespace POA_SIO
{
  

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_sh.cpp:76

  class Receiver;
  typedef Receiver *Receiver_ptr;

  class  Receiver
    : public virtual PortableServer::ServantBase
  {
  protected:
    Receiver (void);
  
  public:
    /// Useful for template programming.
    typedef ::SIO::Receiver _stub_type;
    typedef ::SIO::Receiver_ptr _stub_ptr_type;
    typedef ::SIO::Receiver_var _stub_var_type;

    Receiver (const Receiver& rhs);
    virtual ~Receiver (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::SIO::Receiver *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_sh.cpp:39

    virtual void recv (
      const char * text) = 0;

    static void recv_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);

    // TAO_IDL - Generated from
    // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_sh.cpp:39

    virtual void event (
      ::CORBA::Long ev) = 0;

    static void event_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

  // TAO_IDL - Generated from
  // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_sh.cpp:76

  class FPGA;
  typedef FPGA *FPGA_ptr;

  class  FPGA
    : public virtual PortableServer::ServantBase
  {
  protected:
    FPGA (void);
  
  public:
    /// Useful for template programming.
    typedef ::SIO::FPGA _stub_type;
    typedef ::SIO::FPGA_ptr _stub_ptr_type;
    typedef ::SIO::FPGA_var _stub_var_type;

    FPGA (const FPGA& rhs);
    virtual ~FPGA (void);

    virtual ::CORBA::Boolean _is_a (const char* logical_type_id);

    virtual void _dispatch (
        TAO_ServerRequest & req,
        TAO::Portable_Server::Servant_Upcall *servant_upcall);
    
    ::SIO::FPGA *_this (void);
    
    virtual const char* _interface_repository_id (void) const;

    // TAO_IDL - Generated from
    // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_sh.cpp:39

    virtual ::CORBA::Boolean connect (
      ::SIO::Receiver_ptr receiver) = 0;

    static void connect_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);

    // TAO_IDL - Generated from
    // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_sh.cpp:39

    virtual ::CORBA::Boolean disconnect (
      ::SIO::Receiver_ptr receiver) = 0;

    static void disconnect_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);

    // TAO_IDL - Generated from
    // c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_sh.cpp:39

    virtual ::CORBA::Boolean send (
      const char * text,
      ::CORBA::String_out reply) = 0;

    static void send_skel (
        TAO_ServerRequest &server_request,
        TAO::Portable_Server::Servant_Upcall *servant_upcall,
        TAO_ServantBase *servant);
  };

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_sh.cpp:69

} // module SIO

#include /**/ "ace/post.h"

#endif /* ifndef */

