// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.1.9
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:376


#include "tofC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "tofC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for TOF::Session.

TOF::Session_ptr
TAO::Objref_Traits<TOF::Session>::duplicate (
    TOF::Session_ptr p)
{
  return TOF::Session::_duplicate (p);
}

void
TAO::Objref_Traits<TOF::Session>::release (
    TOF::Session_ptr p)
{
  ::CORBA::release (p);
}

TOF::Session_ptr
TAO::Objref_Traits<TOF::Session>::nil (void)
{
  return TOF::Session::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<TOF::Session>::marshal (
    const TOF::Session_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_cs.cpp:91

void
TOF::Session::debug (
  const ::CORBA::WChar * text,
  const ::CORBA::WChar * key)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::WChar *>::in_arg_val _tao_text (text);
  TAO::Arg_Traits< ::CORBA::WChar *>::in_arg_val _tao_key (key);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_text,
      &_tao_key
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "debug",
      5,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_cs.cpp:91

::CORBA::Boolean
TOF::Session::setControlMethod (
  const ::TOF::ControlMethod & method,
  const char * hint)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  TAO::Arg_Traits< ::TOF::ControlMethod>::in_arg_val _tao_method (method);
  TAO::Arg_Traits< char *>::in_arg_val _tao_hint (hint);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_method,
      &_tao_hint
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "setControlMethod",
      16,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_operation\operation_cs.cpp:91

::SIO::FPGA_ptr
TOF::Session::get_fpga_sio (
  void)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< ::SIO::FPGA>::ret_val _tao_retval;

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "get_fpga_sio",
      12,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
    );

  _tao_call.invoke (0, 0);

  return _tao_retval.retn ();
}

TOF::Session::Session (void)
{
}

TOF::Session::~Session (void)
{
}

void
TOF::Session::_tao_any_destructor (void *_tao_void_pointer)
{
  Session *_tao_tmp_pointer =
    static_cast<Session *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

TOF::Session_ptr
TOF::Session::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Session>::narrow (
        _tao_objref,
        "IDL:TOF/Session:1.0");
}

TOF::Session_ptr
TOF::Session::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<Session>::unchecked_narrow (
        _tao_objref);
}

TOF::Session_ptr
TOF::Session::_nil (void)
{
  return 0;
}

TOF::Session_ptr
TOF::Session::_duplicate (Session_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
TOF::Session::_tao_release (Session_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
TOF::Session::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:Instrument/Session:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:TOF/Session:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* TOF::Session::_interface_repository_id (void) const
{
  return "IDL:TOF/Session:1.0";
}

::CORBA::Boolean
TOF::Session::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_typecode\objref_typecode.cpp:72

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_TOF_Session (
    ::CORBA::tk_objref,
    "IDL:TOF/Session:1.0",
    "Session");
  

namespace TOF
{
  ::CORBA::TypeCode_ptr const _tc_Session =
    &_tao_tc_TOF_Session;
}

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\any_op_cs.cpp:41
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<TOF::Session>::to_object (
      ::CORBA::Object_ptr &_tao_elem) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace TOF
{
  

  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Session_ptr _tao_elem)
  {
    Session_ptr _tao_objptr =
      Session::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }

  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      Session_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<Session>::insert (
        _tao_any,
        Session::_tao_any_destructor,
        _tc_Session,
        *_tao_elem);
  }

  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      Session_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<Session>::extract (
          _tao_any,
          Session::_tao_any_destructor,
          _tc_Session,
          _tao_elem);
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    TOF::Session_ptr _tao_elem)
{
  TOF::Session_ptr _tao_objptr =
    TOF::Session::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    TOF::Session_ptr *_tao_elem)
{
  TAO::Any_Impl_T<TOF::Session>::insert (
      _tao_any,
      TOF::Session::_tao_any_destructor,
      TOF::_tc_Session,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    TOF::Session_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<TOF::Session>::extract (
        _tao_any,
        TOF::Session::_tao_any_destructor,
        TOF::_tc_Session,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// c:\users\toshi\src\vc11\ace_wrappers\tao\tao_idl\be\be_visitor_interface\cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const TOF::Session_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    TOF::Session_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::TOF::Session RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



