#!/bin/sh

echo "acqirisd post installation...."

if [ "$1" = "configure" ]; then
    mv /etc/init.d/acqirisd.sh /etc/init.d/acqirisd
    chmod 755 /etc/init.d/acqirisd
    update-rc.d acqirisd defaults 81
    /etc/init.d/acqirisd restart
fi
