
add_library( FileParsers SHARED IMPORTED )
add_library( GraphMol    SHARED IMPORTED )
add_library( SmilesParse SHARED IMPORTED )
add_library( RDGeneral   SHARED IMPORTED )
add_library( RDGeometryLib SHARED IMPORTED )
add_library( SubstructMatch SHARED IMPORTED )
add_library( Depictor    SHARED IMPORTED )
add_library( Descriptors SHARED IMPORTED )

if ( APPLE )
  set( SO "dylib" )
else()
  set( SO "so" )
endif()

set_target_properties( FileParsers PROPERTIES IMPORTED_LOCATION ${rdkit_DIR}/lib/libFileParsers.${SO} )
set_target_properties( GraphMol    PROPERTIES IMPORTED_LOCATION ${rdkit_DIR}/lib/libGraphMol.${SO} )
set_target_properties( SmilesParse PROPERTIES IMPORTED_LOCATION ${rdkit_DIR}/lib/libSmilesParse.${SO} )
set_target_properties( RDGeneral   PROPERTIES IMPORTED_LOCATION ${rdkit_DIR}/lib/libRDGeneral.${SO} )
set_target_properties( RDGeometryLib  PROPERTIES IMPORTED_LOCATION ${rdkit_DIR}/lib/libRDGeometryLib.${SO} )
set_target_properties( SubstructMatch PROPERTIES IMPORTED_LOCATION ${rdkit_DIR}/lib/libSubstructMatch.${SO} )
set_target_properties( Depictor    PROPERTIES IMPORTED_LOCATION ${rdkit_DIR}/lib/libDepictor.${SO} )
set_target_properties( Descriptors PROPERTIES IMPORTED_LOCATION ${rdkit_DIR}/lib/libDescriptors.${SO} )