#ifndef ADICONTROLS_GLOBAL_H
#define ADICONTROLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADICONTROLS_LIBRARY)
#  define ADICONTROLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADICONTROLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADICONTROLS_GLOBAL_H
