#ifndef TOFCONTROLLER_GLOBAL_H
#define TOFCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TOFCONTROLLER_LIBRARY)
#  define TOFCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TOFCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TOFCONTROLLER_GLOBAL_H
